services:
  postgres:
    build: .
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql